theme: jekyll-theme-cayman

title: aaa
url: https://github.com/pieea/blog
tagline: abc
description: ccc
author: piee
show_downloads: false

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-mentions
  - jekyll-seo-tag

paginate: 5
paginate_path: "/blog/page:num/"